Repository dotnet/performance, pull requests merged in 2021-11, with the labels that each got.

#2112 Add Maui iOS and MacCatalyst Performance SOD tests
  src/scenarios/mauiios/post.py
  src/scenarios/mauiios/pre.py
  src/scenarios/mauiios/test.py
  src/scenarios/mauimaccatalyst/post.py
  src/scenarios/mauimaccatalyst/pre.py
  src/scenarios/mauimaccatalyst/test.py
Labels: enhancement, Scenario

#2127 Reenable Cbor tests.
  src/benchmarks/micro/libraries/System.Formats.Cbor/CoseKeyHelpers.cs
  src/benchmarks/micro/libraries/System.Formats.Cbor/Perf.CborReader.cs
  src/benchmarks/micro/libraries/System.Formats.Cbor/Perf.CborWriter.cs
Labels: bug, impact test coverage, reenable

#2141 Disable the compilation of the Perf.Regex.Industry.cs
  src/benchmarks/micro/MicroBenchmarks.csproj
Labels: bug, impact test coverage

#2117 Perf Scripts Fail if Results Upload Fails
  scripts/benchmarks_ci.py
  src/scenarios/shared/sod.py
  src/scenarios/shared/startup.py
Labels: bug, lab-infrastructure

#2150 Change reenable regex industry tests.
  src/benchmarks/micro/MicroBenchmarks.csproj
  src/benchmarks/micro/libraries/System.Text.RegularExpressions/Perf.Regex.Industry.cs
Labels: bug, impact test coverage
