Repository dotnet/performance, pull requests merged in 2021-09, with the labels that each got.

#1968 Re-enable blazor wasm hot reload
  eng/performance/sdk_scenarios.proj
Labels: bug, Scenario

#1970 Fix Nuget Security Analysis Failure in release/5.0.1xx
  src/benchmarks/other/dmlib/Nuget.config
Labels: lab-infrastructure

#1988 Fix Path String for SDK Web Large 2.0 and 3.0 Scenarios
  src/scenarios/weblarge2.0/pre.py
  src/scenarios/weblarge3.0/pre.py
Labels: bug, lab-infrastructure

#2019 Remove Failure Reporting Code from performance Repo
  eng/performance/benchmark_jobs.yml
  eng/performance/scenarios.yml
  scripts/benchmarks_ci.py
  src/scenarios/shared/startup.py
  src/tools/Reporting/FailureReporting/FailureReporter.cs
  src/tools/Reporting/FailureReporting/FailureReporting.csproj
Labels: lab-infrastructure
