Repository dotnet/performance, pull requests merged in 2022-03, with the labels that each got.

#2295 [MAUI] Enable iOS ipa file size measurement
  src/scenarios/helloios/pre.py
  src/scenarios/mauiios/pre.py
Labels: enhancement

#2296 Increase the build timeout
  scripts/micro_benchmarks.py
Labels: WRI

#2314 Add Parameter Filter
  .gitignore
  src/benchmarks/micro/Program.cs
  src/harness/BenchmarkDotNet.Extensions/CommandLineOptions.cs
  src/harness/BenchmarkDotNet.Extensions/ParameterFilter.cs
  src/harness/BenchmarkDotNet.Extensions/RecommendedConfig.cs
Labels: enhancement

#2320 Fixes for wasm builds
  scripts/benchmarks_ci.py
  scripts/ci_setup.py
  scripts/dotnet.py
  src/benchmarks/micro/MicroBenchmarks.Wasm.targets
Labels: bug, python, pipeline blocker
