Repository dotnet/performance, pull requests merged in 2022-11, with the labels that each got.

#2685 Removed .rt from the CentOS.
  azure-pipelines.yml
  src/benchmarks/micro/libraries/Microsoft.Extensions.Configuration/ConfigurationBinderBenchmarks.cs
Labels: lab-infrastructure

#2686 Backport of #2685 to release/7.0, fixes nativeAot run and changes centos queue.
  azure-pipelines.yml
  src/benchmarks/micro/libraries/Microsoft.Extensions.Configuration/ConfigurationBinderBenchmarks.cs
Labels: lab-infrastructure

#2585 [Net8.0] Update channel_map with net8 and organized 6v7v8 groupings.
  eng/performance/benchmark_jobs.yml
  eng/performance/scenarios.yml
  scripts/channel_map.py
  src/benchmarks/micro/MicroBenchmarks.csproj
Labels: enhancement, dependencies

#2672 Add Bepuphysics benchmarks
  src/benchmarks/real-world/bepuphysics2/BenchmarkHelper.cs
  src/benchmarks/real-world/bepuphysics2/CollisionBatcherTaskBenchmarks.cs
  src/benchmarks/real-world/bepuphysics2/ConvexCollisionTesterBenchmarks.cs
  src/benchmarks/real-world/bepuphysics2/DemoBenchmarks.csproj
  src/benchmarks/real-world/bepuphysics2/FourBodyConstraintBenchmarks.cs
  src/benchmarks/real-world/bepuphysics2/GatherScatterBenchmarks.cs
  src/benchmarks/real-world/bepuphysics2/GroupedCollisionTesterBenchmarks.cs
  src/benchmarks/real-world/bepuphysics2/OneBodyConstraintBenchmarks.cs
  src/benchmarks/real-world/bepuphysics2/OneBodyConstraintBenchmarksDeep.cs
  src/benchmarks/real-world/bepuphysics2/Program.cs
  src/benchmarks/real-world/bepuphysics2/README.md
  src/benchmarks/real-world/bepuphysics2/RagdollTubeBenchmark.cs
  src/benchmarks/real-world/bepuphysics2/ShapePileBenchmark.cs
  src/benchmarks/real-world/bepuphysics2/ShapeRayBenchmarks.cs
  src/benchmarks/real-world/bepuphysics2/ShapeRayBenchmarksDeep.cs
  src/benchmarks/real-world/bepuphysics2/SweepBenchmarks.cs
  src/benchmarks/real-world/bepuphysics2/SweepBenchmarksDeep.cs
  src/benchmarks/real-world/bepuphysics2/THIRD_PARTY_NOTICES.TXT
  src/benchmarks/real-world/bepuphysics2/ThreeBodyConstraintBenchmarks.cs
  src/benchmarks/real-world/bepuphysics2/TwoBodyConstraintBenchmarks.cs
  src/benchmarks/real-world/bepuphysics2/TwoBodyConstraintBenchmarksDeep.cs
Labels: adds new benchmarks

#2149 Add ImageSharp benchmark
  src/benchmarks/real-world/ImageSharp/Codecs/DecodeBmp.cs
  src/benchmarks/real-world/ImageSharp/Codecs/DecodeFilteredPng.cs
  src/benchmarks/real-world/ImageSharp/Codecs/DecodeGif.cs
  src/benchmarks/real-world/ImageSharp/Codecs/DecodePng.cs
  src/benchmarks/real-world/ImageSharp/Codecs/DecodeTga.cs
  src/benchmarks/real-world/ImageSharp/Codecs/EncodeBmp.cs
  src/benchmarks/real-world/ImageSharp/Codecs/EncodeGif.cs
  src/benchmarks/real-world/ImageSharp/Codecs/EncodeIndexedPng.cs
  src/benchmarks/real-world/ImageSharp/Codecs/EncodePng.cs
  src/benchmarks/real-world/ImageSharp/Codecs/EncodeTga.cs
  src/benchmarks/real-world/ImageSharp/Codecs/Jpeg/DecodeJpeg.cs
  src/benchmarks/real-world/ImageSharp/ImageSharp.Benchmarks.csproj
  src/benchmarks/real-world/ImageSharp/Images/Input/Bmp/Car.bmp
  src/benchmarks/real-world/ImageSharp/Images/Input/Gif/rings.gif
  src/benchmarks/real-world/ImageSharp/Images/Input/Jpg/baseline/640px-Unequalized_Hawkes_Bay_NZ.jpg
  src/benchmarks/real-world/ImageSharp/Images/Input/Jpg/baseline/Hiyamugi.jpg
  src/benchmarks/real-world/ImageSharp/Images/Input/Jpg/baseline/Lake.jpg
  src/benchmarks/real-world/ImageSharp/Images/Input/Jpg/baseline/Snake.jpg
  src/benchmarks/real-world/ImageSharp/Images/Input/Jpg/baseline/jpeg400jfif.jpg
  src/benchmarks/real-world/ImageSharp/Images/Input/Jpg/baseline/jpeg420exif.jpg
  src/benchmarks/real-world/ImageSharp/Images/Input/Jpg/baseline/winter444_interleaved.jpg
  src/benchmarks/real-world/ImageSharp/Images/Input/Jpg/issues/Issue518-Bad-RST-Progressive.jpg
  src/benchmarks/real-world/ImageSharp/Images/Input/Jpg/progressive/winter420_noninterleaved.jpg
  src/benchmarks/real-world/ImageSharp/Images/Input/Png/filter0.png
  src/benchmarks/real-world/ImageSharp/Images/Input/Png/filter1.png
  src/benchmarks/real-world/ImageSharp/Images/Input/Png/filter2.png
  src/benchmarks/real-world/ImageSharp/Images/Input/Png/filter3.png
  src/benchmarks/real-world/ImageSharp/Images/Input/Png/filter4.png
  src/benchmarks/real-world/ImageSharp/Images/Input/Png/rgb-48bpp.png
  src/benchmarks/real-world/ImageSharp/Images/Input/Png/splash.png
  src/benchmarks/real-world/ImageSharp/Images/Input/Tga/targa_24bit.tga
  src/benchmarks/real-world/ImageSharp/Processing/BokehBlur.cs
  src/benchmarks/real-world/ImageSharp/Processing/Crop.cs
  src/benchmarks/real-world/ImageSharp/Processing/DetectEdges.cs
  src/benchmarks/real-world/ImageSharp/Processing/Diffuse.cs
  src/benchmarks/real-world/ImageSharp/Processing/GaussianBlur.cs
  src/benchmarks/real-world/ImageSharp/Processing/HistogramEqualization.cs
  src/benchmarks/real-world/ImageSharp/Processing/Resize.cs
  src/benchmarks/real-world/ImageSharp/Processing/Rotate.cs
  src/benchmarks/real-world/ImageSharp/Program.cs
  src/benchmarks/real-world/ImageSharp/README.md
  src/benchmarks/real-world/ImageSharp/THIRD-PARTY-NOTICES
  src/benchmarks/real-world/ImageSharp/TestUtilities/TestDataGenerator.cs
  src/benchmarks/real-world/ImageSharp/TestUtilities/TestEnvironment.cs
  src/benchmarks/real-world/ImageSharp/TestUtilities/TestImages.cs
  src/harness/BenchmarkDotNet.Extensions/RecommendedConfig.cs
Labels: adds new benchmarks

#2692 [Release7.0] Update Scenario prepare dotnet version used
  eng/performance/scenarios.yml
Labels: bug, lab-infrastructure

#2693 Update releases/7.0 badges to point to release/7.0 builds.
  README.md
Labels: documentation

#2694 Add release/7.0 badges to main readme.
  README.md
Labels: documentation

#2679 Vector128 microbenchmarks
  src/benchmarks/micro/libraries/System.Runtime.Intrinsics/Perf_Vector128.cs
  src/benchmarks/micro/libraries/System.Runtime.Intrinsics/Perf_Vector128OfT.cs
Labels: adds new benchmarks

#2705 Update markdowns to net8.0.
  docs/basic-scenarios.md
  docs/benchmarkdotnet.md
  docs/benchmarking-workflow-dotnet-runtime.md
  docs/blazor-scenarios.md
  docs/profiling-workflow-dotnet-runtime.md
  docs/scenarios-workflow.md
  docs/sdk-scenarios.md
  src/benchmarks/gc/docs/example.md
  src/benchmarks/gc/docs/modifying_and_testing_gcperfsim.md
  src/benchmarks/micro/README.md
Labels: documentation

#2720 [Release/3.1.4xx] backport#1936 by disabling Pipeline Reporter
  eng/performance/helix.proj
  eng/performance/scenarios.proj
  eng/performance/sdk_scenarios.proj
Labels: bug, enhancement

#2704 Update channel map to have net6.0 tfm match 6.0 branch before master channel + update 6.0 branch
  scripts/channel_map.py
Labels: bug, dependencies

#2741 Bump BDN version to include recent bug fixes
  eng/Versions.props
  src/benchmarks/micro/Program.cs
  src/benchmarks/real-world/ILLink/BasicBenchmark.cs
  src/benchmarks/real-world/ILLink/MSBuildBenchmark.cs
  src/benchmarks/real-world/ILLink/Program.cs
  src/harness/BenchmarkDotNet.Extensions/RecommendedConfig.cs
Labels: dependencies
