Repository dotnet/performance, pull requests merged in 2022-10, with the labels that each got.

#2616 Support for explicit output for build and publish commands.
  src/scenarios/shared/precommands.py
Labels: enhancement, python

#2581 Basic linker benchmarks
  azure-pipelines.yml
  eng/Version.Details.xml
  eng/Versions.props
  src/benchmarks/real-world/ILLink/BasicBenchmark.cs
  src/benchmarks/real-world/ILLink/ILLinkBenchmarks.csproj
  src/benchmarks/real-world/ILLink/MSBuildBenchmark.cs
  src/benchmarks/real-world/ILLink/Program.cs
  src/benchmarks/real-world/ILLink/SampleProject/.gitignore
  src/benchmarks/real-world/ILLink/SampleProject/HelloWorld.template.csproj
  src/benchmarks/real-world/ILLink/SampleProject/Program.cs
  src/benchmarks/real-world/ILLink/Utilities.cs
Labels: adds new benchmarks

#2652 [MAUI] Remove Maui desktop tests from Arm
  eng/performance/scenarios.proj
Labels: bug, pipeline blocker, impact test coverage, reenable

#2658 Add Environment namespace to fix specialfolderoptions not found.
  src/benchmarks/micro/libraries/System.IO.FileSystem/Perf.File.cs
Labels: pipeline blocker
