Repository dotnet/performance, pull requests merged in 2022-06, with the labels that each got.

#2474 Update deprecated getLogger().warn to getLogger().warning.
  scripts/benchmarks_ci.py
Labels: enhancement

#2468 Add release/6.0 to performance-ci runs and add Maui WinUI
  azure-pipelines-gc.yml
  azure-pipelines.yml
  eng/performance/benchmark_jobs.yml
  eng/performance/pr.yml
  eng/performance/scenarios.proj
  eng/performance/scenarios.yml
  scripts/channel_map.py
  scripts/dotnet.py
  scripts/performance/common.py
  src/scenarios/mauidesktop/post.py
  src/scenarios/mauidesktop/pre.py
  src/scenarios/mauidesktop/test.py
  src/scenarios/shared/precommands.py
  src/tools/ScenarioMeasurement/Startup/Startup.cs
  src/tools/ScenarioMeasurement/Startup/WinUIParser.cs
Labels: enhancement

#2492 [wasm] Fix wasm perf runs
  src/benchmarks/micro/MicroBenchmarks.Wasm.targets
Labels: pipeline blocker, reenable

#2490 Add MauiVersion to Maui Desktop testing and Cleanup Maui Desktop testing
  eng/performance/scenarios.proj
  src/scenarios/mauidesktop/pre.py
  src/scenarios/mauidesktop/test.py
  src/tools/Reporting/Reporting/Reporter.cs
Labels: enhancement

#2511 Set version for notebook for Jupyter notebooks.
  src/benchmarks/gc/src/requirements.txt
Labels: dependencies
