Repository dotnet/performance, pull requests merged in 2022-08, with the labels that each got.

#2533 Add TAR async benchmarks
  src/benchmarks/micro/libraries/System.Formats.Tar/Perf.TarFile.cs
Labels: *NO MERGE*

#2527 Remove unneeded centos yum install
  eng/performance/benchmark_jobs.yml
Labels: enhancement, dependencies

#2393 Maui win UI startup testing
  eng/performance/scenarios.proj
  scripts/dotnet.py
  src/scenarios/mauiblazordesktop/post.py
  src/scenarios/mauiblazordesktop/pre.py
  src/scenarios/mauiblazordesktop/src/Replacement.Index.razor.cs
  src/scenarios/mauiblazordesktop/test.py
  src/scenarios/mauidesktop/post.py
  src/scenarios/mauidesktop/pre.py
  src/scenarios/mauidesktop/test.py
  src/scenarios/shared/precommands.py
  src/tools/ScenarioMeasurement/Startup/Startup.cs
  src/tools/ScenarioMeasurement/Startup/WinUIBlazorParser.cs
  src/tools/ScenarioMeasurement/Startup/WinUIParser.cs
Labels: enhancement

#2572 Add benchmark for large number of ConfigurationProvider
  src/benchmarks/micro/MicroBenchmarks.csproj
  src/benchmarks/micro/libraries/Microsoft.Extensions.Configuration/ConfigurationBinderBenchmarks.cs
Labels: adds new benchmarks

#2517 Add If statement benchmarks
  src/benchmarks/micro/runtime/Statements/If.cs
Labels: adds new benchmarks

#2583 Add release/7.0 channel to channel map
  scripts/channel_map.py
Labels: bug, enhancement, pipeline blocker

#2336 Adds benchmarks for GetChildKeys
  src/benchmarks/micro/libraries/Microsoft.Extensions.Configuration/GetChildKeysTests.cs
Labels: adds new benchmarks
