Repository dotnet/performance, pull requests merged in 2023-11, with the labels that each got.

#3463 Update benchmarks_local default framework from net8.0 -> net9.0.
  scripts/benchmarks_local.py
Labels: enhancement

#3466 Add benchmarks for BigInteger.Equals
  src/benchmarks/micro/libraries/System.Runtime.Numerics/Perf.BigInteger.cs
Labels: adds new benchmarks

#3457 Update ComWrapper.ParallelRCWLookup loop count
  src/benchmarks/micro/runtime/Interop/ComWrappers.cs
Labels: enhancement

#3468 Add initial README for the benchmarks_local.py script.
  scripts/BENCHMARKS_LOCAL_README.md
  scripts/benchmarks_local.py
Labels: enhancement

#3479 Fix Blazor iOS Maui Package Failure
  src/scenarios/mauiblazorios/pre.py
Labels: bug

#3485 Fix startup affinity check bug and set bug
  src/tools/ScenarioMeasurement/Startup/Startup.cs
Labels: bug

#3410 Adding benchmarks from Akade.IndexedSet
  azure-pipelines.yml
  src/benchmarks/real-world/Akade.IndexedSet.Benchmarks/Akade.IndexedSet.Benchmarks.csproj
  src/benchmarks/real-world/Akade.IndexedSet.Benchmarks/Categories.cs
  src/benchmarks/real-world/Akade.IndexedSet.Benchmarks/ConcurrentSetBenchmarks.cs
  src/benchmarks/real-world/Akade.IndexedSet.Benchmarks/FullTextIndexBenchmarks.cs
  src/benchmarks/real-world/Akade.IndexedSet.Benchmarks/MultiValueIndexBenchmarks.cs
  src/benchmarks/real-world/Akade.IndexedSet.Benchmarks/PrefixIndexBenchmarks.cs
  src/benchmarks/real-world/Akade.IndexedSet.Benchmarks/Program.cs
  src/benchmarks/real-world/Akade.IndexedSet.Benchmarks/README.md
  src/benchmarks/real-world/Akade.IndexedSet.Benchmarks/RangeIndexBenchmarks.cs
  src/benchmarks/real-world/Akade.IndexedSet.Benchmarks/RealWorld/EventSourcedAggregateCache/AggregateAndEvents.cs
  src/benchmarks/real-world/Akade.IndexedSet.Benchmarks/RealWorld/EventSourcedAggregateCache/DataGenerator.cs
  src/benchmarks/real-world/Akade.IndexedSet.Benchmarks/RealWorld/EventSourcedAggregateCache/EventHandlers.cs
  src/benchmarks/real-world/Akade.IndexedSet.Benchmarks/RealWorld/EventSourcedAggregateCache/QueryBenchmarks.cs
  src/benchmarks/real-world/Akade.IndexedSet.Benchmarks/RealWorld/EventSourcedAggregateCache/RehydrationBenchmark.cs
  src/benchmarks/real-world/Akade.IndexedSet.Benchmarks/UniqueLookupBenchmarks.cs
  src/benchmarks/real-world/RealWorldBenchmarks.sln
Labels: adds new benchmarks

#3513 Update the Illink Sample benchmark to support the PERFLAB_TARGET_FRAMEWORKS
  src/benchmarks/real-world/ILLink/SampleProject/HelloWorld.template.csproj
  src/benchmarks/real-world/ILLink/Utilities.cs
Labels: enhancement

#3348 Add CountBy and AggregateBy benchmarks
  src/benchmarks/micro/runtime/Linq/Linq.cs
Labels: adds new benchmarks

#3035 Add microbenchmarks for Crc32 and Crc64 algorithms
  src/benchmarks/micro/MicroBenchmarks.csproj
  src/benchmarks/micro/libraries/System.IO.Hashing/Crc32_AppendPerf.cs
  src/benchmarks/micro/libraries/System.IO.Hashing/Crc32_GetCurrentHashPerf.cs
  src/benchmarks/micro/libraries/System.IO.Hashing/Crc64_AppendPerf.cs
  src/benchmarks/micro/libraries/System.IO.Hashing/Crc64_GetCurrentHashPerf.cs
  src/benchmarks/micro/libraries/System.IO.Hashing/Crc_AppendPerf.cs
  src/benchmarks/micro/libraries/System.IO.Hashing/Crc_GetCurrentHashPerf.cs
Labels: adds new benchmarks
