Repository dotnet/performance, pull requests merged in 2023-03, with the labels that each got.

#2923 Update markdownlint.yml versions
  .github/workflows/markdownlint.yml
Labels: dependencies

#2557 add binary xml version to xml benchmarks
  src/benchmarks/micro/Serializers/Xml_FromStream.cs
  src/benchmarks/micro/Serializers/Xml_ToStream.cs
Labels: adds new benchmarks

#2877 Add Android Memory Consumption testing capabilities.
  eng/performance/maui_scenarios_android.proj
  eng/performance/scenarios.yml
  src/scenarios/shared/androidhelper.py
  src/scenarios/shared/const.py
  src/scenarios/shared/memoryconsumption.py
  src/scenarios/shared/runner.py
  src/scenarios/shared/testtraits.py
  src/tools/ScenarioMeasurement/MemoryConsumption/AndroidMemoryParser.cs
  src/tools/ScenarioMeasurement/MemoryConsumption/IParser.cs
  src/tools/ScenarioMeasurement/MemoryConsumption/LinuxTraceSession.cs
  src/tools/ScenarioMeasurement/MemoryConsumption/MemoryConsumption.cs
  src/tools/ScenarioMeasurement/MemoryConsumption/MemoryConsumption.csproj
  src/tools/ScenarioMeasurement/MemoryConsumption/ParserUtility.cs
  src/tools/ScenarioMeasurement/MemoryConsumption/PerfCollect.cs
  src/tools/ScenarioMeasurement/MemoryConsumption/ProfileParser.cs
  src/tools/ScenarioMeasurement/MemoryConsumption/TraceSessionManager.cs
  src/tools/ScenarioMeasurement/MemoryConsumption/TraceSourceManager.cs
  src/tools/ScenarioMeasurement/MemoryConsumption/WindowsTraceSession.cs
Labels: enhancement

#2936 Removed failing System.Drawing tests from net8.0+ runs.
  src/benchmarks/micro/MicroBenchmarks.csproj
Labels: pipeline blocker
