Repository dotnet/performance, pull requests merged in 2023-12, with the labels that each got.

#3530 Add benchmarks for GetCurrentHashAsUInt32 and GetCurrentHashAsUInt64.
  src/benchmarks/micro/libraries/System.IO.Hashing/Crc32_GetCurrentHashPerf.cs
  src/benchmarks/micro/libraries/System.IO.Hashing/Crc64_GetCurrentHashPerf.cs
Labels: adds new benchmarks

#3529 Generalize Android Memory Consumption condition
  eng/performance/maui_scenarios_android.proj
Labels: enhancement

#3554 Update Pixel Windows 10 queues to Windows 11 queues.
  eng/performance/build_machine_matrix.yml
Labels: dependencies

#3586 Fix Blazor Inner Loop Client SDK_Scenario
  src/scenarios/blazorwasminnerloop/src/Pages/SurveyPrompt.razor
  src/scenarios/blazorwasminnerloop/test.py
Labels: bug

#3630 Update from the OSX.1015 queues to the OSX.13 queues.
  eng/performance/build_machine_matrix.yml
  eng/performance/maui_scenarios_ios.proj
  src/scenarios/shared/runner.py
Labels: enhancement

#3566 Fix typo in metric name for BDN.Extensions Duration.
  src/harness/BenchmarkDotNet.Extensions/PerfLabExporter.cs
Labels: bug
