Repository dotnet/performance, pull requests merged in 2023-07, with the labels that each got.

#2950 Half conversion benchmarks
  src/benchmarks/micro/MicroBenchmarks.csproj
  src/benchmarks/micro/libraries/System.Runtime/Perf.Half.cs
Labels: adds new benchmarks

#3116 Remove blazorserver scenario runs
  eng/performance/sdk_scenarios.proj
  src/scenarios/blazorserverinnerloop/pre.py
  src/scenarios/blazorservertemplate/pre.py
Labels: bug

#3117 [wasm] Enable previously disabled benchmark
  src/benchmarks/micro/libraries/System.Memory/MemoryMarshal.cs
Labels: arch-wasm

#3122 Fix mono aot build
  src/benchmarks/micro/MicroBenchmarks.Common.props
  src/benchmarks/micro/MicroBenchmarks.Mono.props
  src/benchmarks/micro/MicroBenchmarks.csproj
Labels: arch-wasm

#3137 Explicitly set dotnet root for building tools
  eng/performance/scenarios.yml
Labels: bug

#3140 Don't run PDN scenarios on x86 systems
  eng/performance/scenarios.proj
  eng/performance/scenarios.yml
  eng/performance/scenarios_affinitized.proj
Labels: bug

#3109 Setup android power consumption test capability
  src/scenarios/shared/androidhelper.py
  src/scenarios/shared/const.py
  src/scenarios/shared/devicepowerconsumption.py
  src/scenarios/shared/memoryconsumption.py
  src/scenarios/shared/runner.py
  src/scenarios/shared/testtraits.py
  src/tools/ScenarioMeasurement/PowerConsumption/AndroidPowerParser.cs
  src/tools/ScenarioMeasurement/PowerConsumption/IParser.cs
  src/tools/ScenarioMeasurement/PowerConsumption/LinuxTraceSession.cs
  src/tools/ScenarioMeasurement/PowerConsumption/ParserUtility.cs
  src/tools/ScenarioMeasurement/PowerConsumption/PerfCollect.cs
  src/tools/ScenarioMeasurement/PowerConsumption/PowerConsumption.cs
  src/tools/ScenarioMeasurement/PowerConsumption/PowerConsumption.csproj
  src/tools/ScenarioMeasurement/PowerConsumption/ProfileParser.cs
  src/tools/ScenarioMeasurement/PowerConsumption/TraceSessionManager.cs
  src/tools/ScenarioMeasurement/PowerConsumption/TraceSourceManager.cs
  src/tools/ScenarioMeasurement/PowerConsumption/WindowsTraceSession.cs
  src/tools/ScenarioMeasurement/ScenarioMeasurement.sln
Labels: adds new benchmarks

#3154 [perf][ios] Use precommands.framework var instead of explicit framework
  src/scenarios/mauiblazorios/pre.py
  src/scenarios/mauiios/pre.py
  src/scenarios/xamarinios/pre.py
Labels: enhancement

#3159 3153 perf scenarios startup tool build failing
  eng/performance/scenarios.yml
Labels: bug, pipeline blocker

#3142 Add basic local testing script that builds and runs benchmarks
  scripts/benchmarks_local.py
Labels: enhancement

#3163 Fix Android bug and Maui builds
  src/scenarios/shared/androidhelper.py
  src/scenarios/shared/mauisharedpython.py
Labels: bug

#3165 [wasm] Replace hash with VERSION.
  src/tools/ScenarioMeasurement/SizeOnDisk/SizeOnDisk.cs
Labels: arch-wasm

#3167 Add `-bl:` argument to the restore command line
  scripts/dotnet.py
  src/scenarios/shared/precommands.py
Labels: arch-wasm

#3179 Cleanup tool build changes
  eng/performance/scenarios.yml
Labels: enhancement
