Repository dotnet/performance, pull requests merged in 2023-05, with the labels that each got.

#2995 Make it so that setup_loggers will only setup 1 logger globally
  scripts/performance/logger.py
Labels: enhancement

#2999 Add Mobile Galaxy Queue for Android Tests
  azure-pipelines.yml
  eng/performance/build_machine_matrix.yml
  eng/performance/maui_scenarios_android.proj
Labels: enhancement

#3011 Pin urllib to version 1.26.15
  eng/performance/benchmark_jobs.yml
  eng/performance/scenarios.yml
Labels: bug, pipeline blocker

#3004 Update centos7 image to net image
  azure-pipelines.yml
  eng/performance/build_machine_matrix.yml
Labels: bug, pipeline blocker

#3019 Upload perf-lab-reports to helix if uploading to our storage
  scripts/benchmarks_ci.py
Labels: enhancement

#3021 Add PERFLAB_DATA_ additional data from EnvVar option.
  src/tools/Reporting/Reporting/Reporter.cs
Labels: enhancement

#3020 Add processor affinity option for BDN runs
  azure-pipelines.yml
  eng/performance/benchmark_jobs.yml
  scripts/ci_setup.py
Labels: enhancement

#3025 Add Environment Variable Support to ci_setup and yml files
  eng/performance/benchmark_jobs.yml
  eng/performance/scenarios.yml
  scripts/ci_setup.py
Labels: enhancement

#3036 Update AffinityParam Assignment based on feedback
  eng/performance/benchmark_jobs.yml
Labels: enhancement

#3038 Add affinity and runEnvVars for MLNET and Roslyn private runs.
  azure-pipelines.yml
Labels: enhancement

#3040 Fix windows forms large test by enabling the binary formatter
  src/scenarios/windowsformslarge/pre.py
Labels: bug

#2926 Micro benchmarks for System.Formats.Tar.TarWriter.WriteEntry
  src/benchmarks/micro/libraries/System.Formats.Tar/Perf.Tar.cs
Labels: adds new benchmarks

#3039 Fix error exception due to Reason not existing
  scripts/dotnet.py
Labels: bug

#3048 Use Range
  src/tools/ScenarioMeasurement/Startup/PDNStartupParser.cs
  src/tools/ScenarioMeasurement/Startup/ParserUtility.cs
Labels: lab-infrastructure

#3049 Simpler 'new' calls
  src/tools/Reporting/Reporting/Reporter.cs
  src/tools/ScenarioMeasurement/SizeOnDisk/SizeOnDisk.cs
  src/tools/ScenarioMeasurement/Startup.Tests/StartupTests.cs
  src/tools/ScenarioMeasurement/Startup/PerfCollect.cs
  src/tools/ScenarioMeasurement/Startup/Startup.cs
Labels: lab-infrastructure

#3050 Method 'LttngInstalled' marked as static
  src/tools/ScenarioMeasurement/Startup/PerfCollect.cs
Labels: lab-infrastructure

#3047 Fix casing of type(s).
  src/tools/Reporting/Reporting/Reporter.cs
  src/tools/ScenarioMeasurement/SizeOnDisk/SizeOnDisk.cs
  src/tools/ScenarioMeasurement/Startup.Tests/StartupTests.cs
  src/tools/ScenarioMeasurement/Startup/DeviceTimeToMain.cs
  src/tools/ScenarioMeasurement/Startup/PerfCollect.cs
  src/tools/ScenarioMeasurement/Startup/Startup.cs
  src/tools/ScenarioMeasurement/Startup/WinUIBlazorParser.cs
  src/tools/ScenarioMeasurement/Startup/WinUIParser.cs
  src/tools/ScenarioMeasurement/Util/ProcessHelper.cs
Labels: lab-infrastructure

#3046 Apply readonly modifier where possible.
  src/tools/Reporting/Reporting/Reporter.cs
  src/tools/ScenarioMeasurement/SizeOnDisk/SizeOnDisk.cs
  src/tools/ScenarioMeasurement/Startup.Tests/StartupTests.cs
  src/tools/ScenarioMeasurement/Startup/InnerLoopParser.cs
  src/tools/ScenarioMeasurement/Startup/LinuxTraceSession.cs
  src/tools/ScenarioMeasurement/Startup/PerfCollect.cs
  src/tools/ScenarioMeasurement/Startup/ProfileParser.cs
  src/tools/ScenarioMeasurement/Startup/TraceSourceManager.cs
  src/tools/ScenarioMeasurement/Startup/WindowsTraceSession.cs
Labels: lab-infrastructure

#3042 Add processor affinity options scenarios
  eng/performance/scenarios.yml
  src/scenarios/shared/runner.py
  src/scenarios/shared/startup.py
  src/scenarios/shared/testtraits.py
  src/tools/ScenarioMeasurement/Startup/Startup.cs
  src/tools/ScenarioMeasurement/Util/ProcessHelper.cs
Labels: enhancement, adds new benchmarks
