Repository dotnet/performance, pull requests merged in 2023-09, with the labels that each got.

#3089 Frozen collection benchmarks
  src/benchmarks/micro/libraries/System.Collections/Contains/ContainsFalse.cs
  src/benchmarks/micro/libraries/System.Collections/Contains/ContainsKeyFalse.cs
  src/benchmarks/micro/libraries/System.Collections/Contains/ContainsKeyTrue.cs
  src/benchmarks/micro/libraries/System.Collections/Contains/ContainsTrue.cs
  src/benchmarks/micro/libraries/System.Collections/Contains/ContainsTrueComparer.cs
  src/benchmarks/micro/libraries/System.Collections/Create/CtorFromCollection.cs
  src/benchmarks/micro/libraries/System.Collections/Frozen/Perf_Frozen.cs
  src/benchmarks/micro/libraries/System.Collections/Frozen/Perf_FrozenDictionary_String.cs
  src/benchmarks/micro/libraries/System.Collections/Iterate/IterateForEach.cs
  src/benchmarks/micro/libraries/System.Collections/TryGetValue/TryGetValueFalse.cs
  src/benchmarks/micro/libraries/System.Collections/TryGetValue/TryGetValueTrue.cs
  src/harness/BenchmarkDotNet.Extensions/ValuesGenerator.cs
Labels: adds new benchmarks

#3323 Add missing documentation lines for command-line arguments
  src/benchmarks/gc/src/exec/GCPerfSim/GCPerfSim.cs
Labels: gc-infrastructure

#3302 Add Xamarin android default app run to maui_android runs.
  eng/performance/maui_scenarios_android.proj
  src/scenarios/netandroid/post.py
  src/scenarios/netandroid/pre.py
  src/scenarios/netandroid/test.py
Labels: enhancement

#3263 [perf] Add hybrid globalization performance measurements for Maui scenarios
  azure-pipelines.yml
  eng/performance/maui_scenarios_ios.proj
  eng/performance/scenarios.yml
  eng/performance/send-to-helix.yml
  src/scenarios/shared/precommands.py
Labels: enhancement

#3346 [perf] Fix hybrid globalization command line parameter
  eng/performance/maui_scenarios_ios.proj
Labels: bug

#3354 Update dotnet secret manager tool version
  .config/dotnet-tools.json
Labels: pipeline blocker

#3363 Fix default repo_storage_path with os.getcwd
  scripts/benchmarks_local.py
Labels: bug

#3211 add tests for ReceiveFrom and SendTo
  src/benchmarks/micro/libraries/System.Net.Sockets/Perf.Socket.cs
Labels: adds new benchmarks
