Repository dotnet/performance, pull requests merged in 2023-02, with the labels that each got.

#2880 Update JupyterLab
  src/benchmarks/gc/src/analyze_requirements.txt
  src/benchmarks/gc/src/requirements.txt
Labels: dependencies

#2884 Update maui net8.0 android build
  eng/performance/maui_scenarios_android.proj
  src/scenarios/mauiandroid/pre.py
  src/scenarios/mauiandroidpodcast/pre.py
  src/scenarios/mauiblazorandroid/pre.py
Labels: bug

#2894 [wasm] Update docs to add `--run-isolated` to the command line
  docs/benchmarking-workflow-dotnet-runtime.md
Labels: documentation, arch-wasm

#2899 Add release/8.0-previewX channel maps for X: 1-4.
  scripts/channel_map.py
Labels: dependencies, python
