Repository dotnet/performance, pull requests merged in 2023-10, with the labels that each got.

#3338 Add MonoAOTLLVM to local script
  scripts/benchmarks_local.py
Labels: enhancement

#3379 Add SearchValues microbenchmarks
  src/benchmarks/micro/MicroBenchmarks.csproj
  src/benchmarks/micro/libraries/System.Buffers/SearchValuesByteTests.cs
  src/benchmarks/micro/libraries/System.Buffers/SearchValuesCharTests.cs
Labels: adds new benchmarks

#3381 Cleanup benchmarks_local.py script
  scripts/benchmarks_ci.py
  scripts/benchmarks_local.py
Labels: enhancement

#3388 Add a ReadWriteIterationsLarge for the large SSLStreamTests
  src/benchmarks/micro/libraries/System.Net.Security/SslStreamTests.cs
Labels: bug

#3393 Disable SslStreamTests LargeReadWriteAsync and LargeWriteReadAsync on Linux
  src/benchmarks/micro/libraries/System.Net.Security/SslStreamTests.cs
Labels: bug

#3000 Added PowerShell real-world benchmarks
  azure-pipelines.yml
  src/benchmarks/real-world/PowerShell.Benchmarks/Categories.cs
  src/benchmarks/real-world/PowerShell.Benchmarks/Engine.Compiler.cs
  src/benchmarks/real-world/PowerShell.Benchmarks/Engine.Parser.cs
  src/benchmarks/real-world/PowerShell.Benchmarks/Engine.ScriptBlock.cs
  src/benchmarks/real-world/PowerShell.Benchmarks/PowerShell.Benchmarks.csproj
  src/benchmarks/real-world/PowerShell.Benchmarks/Program.cs
  src/benchmarks/real-world/PowerShell.Benchmarks/README.md
Labels: adds new benchmarks

#3402 Remove --experimental-wasm-eh argument from the WASM runtype args
  scripts/benchmarks_local.py
Labels: bug

#3421 Fix benchmarks_local filter arg parsing
  scripts/benchmarks_local.py
Labels: bug

#3431 Add option --dont-kill-dotnet-processes to benchmarks_local.py
  scripts/benchmarks_local.py
Labels: enhancement

#3434 Benchmarks_local script: Clarify that bdn-arguments must be passed using =.
  scripts/benchmarks_local.py
Labels: bug

#3447 [perf] Add Maui Podcast app performance measurements
  eng/performance/maui_scenarios_ios.proj
  src/scenarios/mauiiospodcast/pre.py
Labels: enhancement

#3450 Disable the ComWrapper.ParallelRCWLookup test on ARM64.
  src/benchmarks/micro/runtime/Interop/ComWrappers.cs
Labels: reenable

#3452 Fix microbenchmarks build
  src/benchmarks/micro/runtime/Interop/ComWrappers.cs
Labels: arch-wasm

#3455 Update IPAName for iOS Podcast to fix unzipped tests.
  eng/performance/maui_scenarios_ios.proj
Labels: bug
