Repository dotnet/performance, pull requests merged in 2023-08, with the labels that each got.

#3222 Revert https://github.com/dotnet/performance/commit/860d6a17d0c17592e2f4d803038d99969f3d8778
  eng/performance/scenarios.yml
Labels: bug

#3250 Add MicrosoftDotNetXHarnessCLIVersion to the maui iOS test proj.
  eng/performance/maui_scenarios_ios.proj
Labels: dependencies

#3268 Fix run configurations only saving as wasm or tiered
  scripts/ci_setup.py
Labels: bug

#3276 Remove wrong comment.
  scripts/dotnet.py
Labels: python

#3272 Add WasmWasm and WasmAOT to local testing script
  scripts/benchmarks_local.py
Labels: enhancement

#3288 [wasm] Don't strip native symbols
  scripts/performance/common.py
  src/benchmarks/micro/MicroBenchmarks.Wasm.props
  src/scenarios/shared/precommands.py
Labels: arch-wasm
