Repository dotnet/performance, pull requests merged in 2023-06, with the labels that each got.

#3056 Add PDN as an affinitized Scenario.
  azure-pipelines.yml
  eng/performance/scenarios.yml
  eng/performance/scenarios_affinitized.proj
  scripts/ci_setup.py
Labels: adds new benchmarks

#3070 Added option for running benchmarks with physical promotion enabled.
  scripts/ci_setup.py
Labels: enhancement, lab-infrastructure

#3072 Add release/6.0-staging to the channel map
  scripts/channel_map.py
Labels: bug

#3071 Add release/7.0-staging to the channel map
  scripts/channel_map.py
Labels: bug

#3076 Mitigate Maui android publish failing due to NETSDK1191
  eng/performance/maui_scenarios_android.proj
Labels: bug

#3077 Use no-self-contained for Maui Android Publish to keep SOD consistent
  eng/performance/maui_scenarios_android.proj
Labels: bug

#3079 Switch to only building Maui Android apps for android-arm64
  eng/performance/maui_scenarios_android.proj
Labels: enhancement

#3092 Adds missing Illink RealWorldRuns, this will provide data for generating Illink arm64 all test history report data
  azure-pipelines.yml
Labels: enhancement, Scenario, Arm64, adds new benchmarks

#3087 Add raising exceptions to retry_on_exception and use for uploading if resource already exists
  scripts/performance/common.py
  scripts/upload.py
Labels: enhancement

#3094 Revert adding Illink arm tests
  azure-pipelines.yml
Labels: Scenario

#3104 Small refactoring around PerfLabGenericEventSource
  src/tools/ScenarioMeasurement/Startup/GenericStartupParser.cs
  src/tools/ScenarioMeasurement/Startup/PDNStartupParser.cs
  src/tools/ScenarioMeasurement/Startup/WinUIBlazorParser.cs
Labels: lab-infrastructure
