Repository dotnet/performance, pull requests merged in 2024-01, with the labels that each got.

#3768 Include the tzinfo in the start time argument when getting the logs from iOS devices
  src/scenarios/shared/runner.py
Labels: bug

#3775 Update urllib to 1.26.18
  eng/performance/benchmark_jobs.yml
  eng/performance/scenarios.yml
  scripts/run_performance_job.py
Labels: dependencies

#3780 Update bootstrap and jquery for weblarge2.0 and weblarge3.0
  src/scenarios/weblarge2.0/src/mvc/wwwroot/lib/bootstrap/LICENSE
  src/scenarios/weblarge2.0/src/mvc/wwwroot/lib/bootstrap/dist/css/bootstrap-theme.css
  src/scenarios/weblarge2.0/src/mvc/wwwroot/lib/bootstrap/dist/css/bootstrap-theme.css.map
  src/scenarios/weblarge2.0/src/mvc/wwwroot/lib/bootstrap/dist/css/bootstrap-theme.min.css
  src/scenarios/weblarge2.0/src/mvc/wwwroot/lib/bootstrap/dist/css/bootstrap-theme.min.css.map
  src/scenarios/weblarge2.0/src/mvc/wwwroot/lib/bootstrap/dist/css/bootstrap.css
  src/scenarios/weblarge2.0/src/mvc/wwwroot/lib/bootstrap/dist/css/bootstrap.css.map
  src/scenarios/weblarge2.0/src/mvc/wwwroot/lib/bootstrap/dist/css/bootstrap.min.css
  src/scenarios/weblarge2.0/src/mvc/wwwroot/lib/bootstrap/dist/css/bootstrap.min.css.map
  src/scenarios/weblarge2.0/src/mvc/wwwroot/lib/bootstrap/dist/js/bootstrap.js
  src/scenarios/weblarge2.0/src/mvc/wwwroot/lib/bootstrap/dist/js/bootstrap.min.js
  src/scenarios/weblarge2.0/src/mvc/wwwroot/lib/jquery/LICENSE.txt
  src/scenarios/weblarge2.0/src/mvc/wwwroot/lib/jquery/dist/jquery.js
  src/scenarios/weblarge2.0/src/mvc/wwwroot/lib/jquery/dist/jquery.min.js
  src/scenarios/weblarge2.0/src/mvc/wwwroot/lib/jquery/dist/jquery.min.map
  src/scenarios/weblarge3.0/src/mvc/wwwroot/lib/bootstrap/LICENSE
  src/scenarios/weblarge3.0/src/mvc/wwwroot/lib/bootstrap/dist/css/bootstrap-theme.css
  src/scenarios/weblarge3.0/src/mvc/wwwroot/lib/bootstrap/dist/css/bootstrap-theme.css.map
  src/scenarios/weblarge3.0/src/mvc/wwwroot/lib/bootstrap/dist/css/bootstrap-theme.min.css
  src/scenarios/weblarge3.0/src/mvc/wwwroot/lib/bootstrap/dist/css/bootstrap-theme.min.css.map
  src/scenarios/weblarge3.0/src/mvc/wwwroot/lib/bootstrap/dist/css/bootstrap.css
  src/scenarios/weblarge3.0/src/mvc/wwwroot/lib/bootstrap/dist/css/bootstrap.css.map
  src/scenarios/weblarge3.0/src/mvc/wwwroot/lib/bootstrap/dist/css/bootstrap.min.css
  src/scenarios/weblarge3.0/src/mvc/wwwroot/lib/bootstrap/dist/css/bootstrap.min.css.map
  src/scenarios/weblarge3.0/src/mvc/wwwroot/lib/bootstrap/dist/js/bootstrap.js
  src/scenarios/weblarge3.0/src/mvc/wwwroot/lib/bootstrap/dist/js/bootstrap.min.js
  src/scenarios/weblarge3.0/src/mvc/wwwroot/lib/jquery/LICENSE.txt
  src/scenarios/weblarge3.0/src/mvc/wwwroot/lib/jquery/dist/jquery.js
  src/scenarios/weblarge3.0/src/mvc/wwwroot/lib/jquery/dist/jquery.min.js
  src/scenarios/weblarge3.0/src/mvc/wwwroot/lib/jquery/dist/jquery.min.map
Labels: enhancement

#3779 For the AoT scenarios, always invoke with allowing to be used with a standalone gc
  src/benchmarks/gc/GC.Infrastructure/Configurations/ASPNetBenchmarks/ASPNetBenchmarks-Aot-Windows.csv
Labels: gc-infrastructure
