Repository dotnet/performance, pull requests merged in 2024-03, with the labels that each got.

#4016 Update BDN Version to fix Wasm Wasm runs and remove Test Adapter to fix WasmAOT runs
  eng/Versions.props
  src/benchmarks/micro/MicroBenchmarks.csproj
Labels: bug, dependencies

#4044 Update BDN version to fix MonoAOT runs.
  eng/Versions.props
Labels: bug

#4054 Only use 8.0 and 9.0 for perf-ci runs on main
  scripts/run_performance_job.py
Labels: bug

#4086 Benchmark Parse/ToString with Large number
  src/benchmarks/micro/libraries/System.Runtime.Numerics/Perf.BigInteger.cs
Labels: adds new benchmarks
