Repository dotnet/performance, pull requests merged in 2024-04, with the labels that each got.

#4103 Fix iOS device startup log starttime bug
  src/scenarios/shared/runner.py
Labels: bug

#4108 Update ImageSharp from version 2.1.3 -> 2.1.7.
  src/benchmarks/real-world/ImageSharp/ImageSharp.Benchmarks.csproj
Labels: dependencies

#4119 [release/7.0] Update GC black requirement.
  src/benchmarks/gc/src/requirements.txt
Labels: dependencies

#4120 [release/6.0] Update GC black requirement.
  src/benchmarks/gc/src/requirements.txt
Labels: dependencies

#4118 Fix Wasm benchmark_local setup
  scripts/benchmarks_local.py
Labels: bug, enhancement

#4079 Add benchmark for WinHttpHandler
  src/benchmarks/micro/MicroBenchmarks.csproj
  src/benchmarks/micro/libraries/System.Net.Http/Perf.WinHttpHandler.cs
Labels: adds new benchmarks

#4151 [Release/7.0] Update runs to use new queues (#4106)
  eng/performance/build_machine_matrix.yml
Labels: dependencies

#4152 [Release/6.0] Update Tiger queues.
  azure-pipelines.yml
Labels: dependencies
