Repository dotnet/performance, pull requests merged in 2025-07, with the labels that each got.

#4875 Update windows open queue to windows11 and VMimage to windows 2025
  eng/pipelines/templates/build-machine-matrix.yml
Labels: enhancement, lab-infrastructure, dependencies

#4885 Update Viper machines to use windows-2025 vm image
  eng/pipelines/templates/build-machine-matrix.yml
Labels: lab-infrastructure, dependencies

#4886 Remove alpine job and cut down on perftiger jobs
  eng/pipelines/runtime-perf-build-jobs.yml
  eng/pipelines/runtime-perf-jobs.yml
  eng/pipelines/templates/run-performance-job.yml
  eng/pipelines/upload-build-artifacts-jobs.yml
  helix.yml
  scripts/run_performance_job.py
Labels: lab-infrastructure

#4888 Remove tiger runs from wasm runtime runs.
  eng/pipelines/runtime-wasm-perf-jobs.yml
Labels: impact test coverage

#4887 run WasmRunWasmOpt
  src/benchmarks/micro/MicroBenchmarks.Wasm.props
Labels: arch-wasm
