Repository dotnet/performance, pull requests merged in 2025-02, with the labels that each got.

#4588 Additional reflection invoke benchmarks
  src/benchmarks/micro/runtime/System.Reflection/Invoke.cs
Labels: adds new benchmarks

#4688 Remove send_certificate_chain arg from ClientAssertionCredential initialization
  scripts/upload.py
Labels: bug

#4703 Update maui versions manually from maui net9.0 repo.
  eng/Version.Details.xml
Labels: bug, dependencies

#4709 Fix NU1510 Error
  src/benchmarks/micro/MicroBenchmarks.csproj
Labels: bug

#4710 Update the runtime jobs we are running
  eng/pipelines/runtime-perf-jobs.yml
  eng/pipelines/runtime-slow-perf-jobs.yml
  eng/pipelines/runtime-wasm-perf-jobs.yml
Labels: Scenario

#4731 Revert "[main] Update dependencies to ensure coherency (#4719)"
  NuGet.config
  eng/Version.Details.xml
  eng/common/core-templates/job/publish-build-assets.yml
  eng/common/sdk-task.ps1
  eng/common/tools.ps1
  global.json
Labels: bug, dependencies

#4730 Disable PerfBDN tests.
  eng/pipelines/templates/runtime-perf-job.yml
  scripts/run_performance_job.py
Labels: temp-pipeline-disable
