Repository dotnet/performance, pull requests merged in 2025-09, with the labels that each got.

#4934 Disable Android package verifier during Android test runs
  src/scenarios/shared/androidhelper.py
  src/scenarios/shared/androidinstrumentation.py
Labels: bug

#4947 Use net9.0_18.5 version 18.5.9219 instead of 18.5.9223.
  NuGet.config
  eng/Version.Details.xml
Labels: dependencies

#4943 Add Partition to SVE micro benchmark
  src/benchmarks/micro/sve/Partition.cs
Labels: adds new benchmarks
